<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Authors>Xpl0itR</Authors>
    <BaseOutputPath>$(SolutionDir)bin/$(MSBuildProjectName)</BaseOutputPath>
    <Copyright>Copyright © 2022-2025 Xpl0itR</Copyright>
    <Description>SystemEx is a library which extends the functionality of the .NET standard libraries.</Description>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <IncludeSymbols>true</IncludeSymbols>
    <IsAotCompatible>true</IsAotCompatible>
    <IsPackable>true</IsPackable>
    <IsTrimmable>true</IsTrimmable>
    <LangVersion>Preview</LangVersion>
    <NoWarn>RS0016;RS0026;RS0027;RS0037</NoWarn>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <PackageId>Xpl0itR.$(MSBuildProjectName)</PackageId>
    <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <TargetFrameworks>netstandard2.1;net5.0;net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <WarningsAsErrors>RS0042</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Diagnostics" Version="8.4.0" />
    <PackageReference Include="CommunityToolkit.HighPerformance" Version="8.4.0" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Roslyn.Diagnostics.Analyzers" Version="3.3.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1' OR '$(TargetFramework)' == 'net5.0'">
    <PackageReference Include="System.Text.Json" Version="9.0.10" />
  </ItemGroup>

</Project>